/**
 * PDF Report Styles and Colors
 * Defines the visual appearance of generated PDF reports
 */

export const colors = {
  // Status colors
  passed: '#22c55e',      // Green
  failed: '#ef4444',      // Red
  warning: '#f59e0b',     // Amber

  // Metric status
  good: '#22c55e',        // Green - within threshold
  caution: '#f59e0b',     // Amber - close to threshold (>80%)
  bad: '#ef4444',         // Red - exceeded threshold

  // General
  primary: '#2563eb',     // Blue
  secondary: '#64748b',   // Slate
  text: '#1e293b',        // Dark slate
  textLight: '#64748b',   // Light slate
  background: '#f8fafc',  // Light gray
  white: '#ffffff',
  border: '#e2e8f0',      // Light border

  // Table
  tableHeader: '#1e40af', // Dark blue
  tableHeaderText: '#ffffff',
  tableRowEven: '#f1f5f9',
  tableRowOdd: '#ffffff',
};

export const fonts = {
  title: 24,
  subtitle: 18,
  heading: 14,
  body: 11,
  small: 9,
  tiny: 8,
};

export const spacing = {
  margin: 50,
  sectionGap: 25,
  paragraphGap: 12,
  lineHeight: 1.4,
};

export const layout = {
  pageWidth: 595.28,  // A4 width in points
  pageHeight: 841.89, // A4 height in points
  contentWidth: 495.28, // pageWidth - 2 * margin
};

export const branding = {
  reportTitle: 'K6 Performance Test Report',
  companyName: 'Performance Engineering Team',
  footerText: 'Generated by K6 Performance Testing Framework',
};

export function getStatusColor(passed, value, threshold) {
  if (passed) {
    // Check if close to threshold (>80%)
    if (threshold && value) {
      const ratio = value / threshold;
      if (ratio > 0.8) {
        return colors.caution;
      }
    }
    return colors.good;
  }
  return colors.bad;
}

export function formatDuration(ms) {
  if (ms < 1000) {
    return `${ms.toFixed(0)}ms`;
  } else if (ms < 60000) {
    return `${(ms / 1000).toFixed(2)}s`;
  } else {
    const minutes = Math.floor(ms / 60000);
    const seconds = ((ms % 60000) / 1000).toFixed(0);
    return `${minutes}m ${seconds}s`;
  }
}

export function formatNumber(num, decimals = 2) {
  if (num === undefined || num === null) return 'N/A';
  if (Number.isInteger(num)) return num.toString();
  return num.toFixed(decimals);
}

export function formatPercentage(value) {
  if (value === undefined || value === null) return 'N/A';
  return `${(value * 100).toFixed(2)}%`;
}

export function formatBytes(bytes) {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${(bytes / Math.pow(k, i)).toFixed(2)} ${sizes[i]}`;
}
